account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.contrib import messages
from . import views
from django.contrib.auth.forms import PasswordChangeForm
from .forms import (
	UserLoginForm, UserPasswordResetForm, UserPasswordChangeForm,
	UserSetPasswordForm,
)


app_name = 'account'


urlpatterns = [
	path('login/', auth_views.LoginView.as_view(
		authentication_form=UserLoginForm,
		template_name='account/login.html',
		), name='login'
	),
	path('logout/', auth_views.LogoutView.as_view(
		next_page='account:login',
		), name='logout'),
	path('password_change/', auth_views.PasswordChangeView.as_view(
			template_name='account/password_change.html',
			form_class=UserPasswordChangeForm,
			success_url=reverse_lazy('account:password_change_done'),
		), name='password_change'
	),
	path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(
			template_name='account/password_change_done.html',	
		), name='password_change_done'
	),
	path('password_reset/', auth_views.PasswordResetView.as_view(
		form_class=UserPasswordResetForm,
		template_name='account/password_reset.html',
		success_url=reverse_lazy('account:password_reset_done'),
		email_template_name='account/password_reset_email.html',
		), 
		name='password_reset'
	),
	path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
		template_name='account/password_reset_done.html'
		), 
		name='password_reset_done'
	),
	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
		form_class=UserSetPasswordForm,
		template_name='account/password_reset_confirm.html',
		success_url=reverse_lazy('account:password_reset_complete'),
		), 
		name='password_reset_confirm'
	),
	path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
		template_name='account/passowrd_reset_complete.html'
		), 
		name='password_reset_complete'
	),
	path('register/', views.UserCreate.as_view(), name='register'),
	path('<slug:username>/', views.ProfileView.as_view(), name='view_profile'),
	path('profile/edit/', views.update_profile, name='edit_profile'),
]

blog/urls.py
from django.urls import path, re_path
from . import views as blog_views

app_name = 'blog'  # Namespace.

urlpatterns = [
    path('', blog_views.PostList.as_view(), name='post_view'),
    path('draft/', blog_views.DraftPostList.as_view(), name='draft_post_view'),
    path('published/', blog_views.PublishedPostList.as_view(), name='published_post_view'),
    path('post/<year>/<month>/<day>/<slug:slug>/', blog_views.DetailsPostView.as_view(), name='post_details_view'),
    path('post/add/', blog_views.PostCreate.as_view(), name='post_add'),
    path('post/<int:pk>/edit/', blog_views.PostUpdate.as_view(), name='post_update'),
    path('post/<int:pk>/published/', blog_views.PostPublish.as_view(), name='post_published'),
    path('post/<int:pk>/delete/', blog_views.PostDelete.as_view(), name='post_delete'),
    path('comment/approve/<int:post_pk>/<int:comment_pk>/', blog_views.ApprovedComment.as_view(), name='comment_approve'),
    path('comment/remove/<int:post_pk>/<int:comment_pk>/', blog_views.RemoveComment.as_view(), name='comment_remove'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import post_save
from django.core.validators import FileExtensionValidator
from website.utils import profile_directory_path


class UserProfile(models.Model):
    # UserProfile Model Manager
    class UserProfileManager(models.Manager):
        def get_dhaka(self):
            return self.filter(city='Dhaka')

    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)
    description = models.TextField(max_length=200)
    city = models.CharField(max_length=50)
    website = models.URLField(max_length=50, blank=True)
    mobile_number = models.CharField(max_length=15, blank=True)
    image = models.ImageField(upload_to=profile_directory_path, blank=True, validators=[
                              FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', ])])

    objects = UserProfileManager()  # Set default QuerySet.

    # success_url for CreateView and UpdateView
    def get_absolute_url(self):
        return reverse('account:view_profile_with_pk', kwargs={'pk': self.pk})

    def __str__(self):
        return self.user.username


"""
Django signals allow decoupled applications get notified when actions 
occur elsewhere in the framework. signals allow certain senders to 
notify a set of receivers that some action has taken place.

post_save signal is sent at the end of a model’s save() method.
sender: The model class.
instance: The actual instance being saved.
created: A boolean; True if a new record was created.
"""


# Alternatively, we can use a @receiver() decorator.
def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])


"""
To receive a signal, register create_profile as a receiver function 
using the post_save.connect() method. The create_profile function is 
called when the post_save signal is sent.
"""
post_save.connect(create_profile, sender=User)  # Listening to signals.

account/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.views.generic.base import RedirectView
from .forms import (
    UserForm, UserUpdateForm, ProfileUpdateForm,
)
# from django.contrib.auth import update_session_auth_hash  # For stay login
from django.contrib.auth import logout
from django.contrib.auth.signals import user_logged_out, user_logged_in
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from website.utils import login_required
from .models import UserProfile
import os


# Message for log out
def logout_message(request, **kwargs):
    html_output = """<p>Hey, You have successfully logged out.
	Thanks for spending some quality time with the Web site today.
	<a href=""" + str(reverse_lazy('account:login')) + """>Log in again</a></p>"""
    messages.info(request, html_output)


user_logged_out.connect(logout_message)


# Message for log in
def login_message(request, **kwargs):
    html_output = """<p>Welcome """ + request.user.username + """! You have successfully logged in. 
	Go to your <a href=""" + str(reverse_lazy('account:view_profile', kwargs={'username': request.user})) + """>Profile</a>.</p>"""
    messages.info(request, html_output)


user_logged_in.connect(login_message)


# This class is used to create user account
class UserCreate(CreateView):
    model = User
    form_class = UserForm
    template_name = 'account/user_form.html'

    # Success url for create and update view.
    def get_success_url(self):
        return reverse_lazy('blog:post_view')

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'Congratulations !\nYou have successfully registered.\nNow you can <a href="' +
                         str(reverse_lazy('account:login')) + '">Log in</a> to access your account')
        return super().form_valid(form)

    def form_invalid(self, form):
        self.object = None
        messages.error(
            self.request, 'Invalid form submission !\nPlease correct the error in below.')
        return super().form_invalid(form)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    # This method accepts a request argument plus arguments, and
    # returns a HTTP response.
    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            messages.error(
                self.request, 'Invalid request !\nYou have already registered.')
            return redirect('account:view_profile', username=self.request.user)
        return super().dispatch(*args, **kwargs)


# This class is used to view user profile
class ProfileView(TemplateView):
    template_name = 'account/user_profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if kwargs:
            # We can use get_object_or_404() instead of try case.
            try:
                context['user'] = User.objects.get(username=kwargs['username'])
            except:
                context['user'] = None
                messages.error(self.request, 'Opps!\nUser is not found.')
        return context

    # Decorate every instance of the class.
    @method_decorator(login_required(login_url='account:login', message="Sorry!\nYou must login to view any profile."))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# This function is used to update user profile
@login_required(login_url='account:login', message="Sorry!\nYou must login to update any profile.")
def update_profile(request, **kwargs):

    profile = UserProfile.objects.get(user=request.user)

    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)

        if request.FILES:
            profile_form = ProfileUpdateForm(
                request.POST, request.FILES, instance=profile)
        else:
            profile_form = ProfileUpdateForm(request.POST, instance=profile)
        if all([user_form.is_valid(), profile_form.is_valid()]):
            # Valid state
            # image attribute contain old image if not select any new
            new_image = request.FILES.get('image')  # New image
            old_image = profile_form.old_image  # Get old image from form
            image_remove_checked = bool(request.POST.get('remove_checked'))
            # Remove image if checked clear
            if image_remove_checked:
                if os.path.isfile(profile.image.path):
                    os.remove(profile.image.path)
                    profile.image = None
            # Remove old image if upload new one
            if new_image:
                if old_image:
                    if os.path.isfile(old_image.path):
                        os.remove(old_image.path)
            user_form.save()
            profile_form.save()
            return redirect('account:view_profile', username=request.user)
        else:
            # Invalid state
            messages.error(
                request, 'Invalid form submission !\nPlease correct the error in below.')
            args = {'user_form': user_form, 'profile_form': profile_form}
            return render(request, 'account/userprofile_update_form.html', args)
    else:
        # GET state
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=profile)
        args = {'user_form': user_form, 'profile_form': profile_form}
        return render(request, 'account/userprofile_update_form.html', args)

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>{% block title %} {% endblock %}</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<!-- Google font-->
	<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
	<!-- Custom CSS-->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'account/css/account.css' %}">

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- Popper JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
	<!-- Confirmation Js -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap-confirmation2/dist/bootstrap-confirmation.min.js"></script>
	<!-- Custom Js -->
	<script src="{% static 'js/custom.js' %}"></script>
	{% block head %} {% endblock %}
</head>
{% load static %}

<body style="background: url({% static 'images/bg.jpg' %}) fixed;">
	<div class="container">
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<a style="font-family: 'Lobster', cursive;" class="navbar-brand" href="/">Community Blog</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
				aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav ml-auto">
					{% block navbar %} {% endblock %}
					{% if request.user.is_authenticated %}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
							data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i
								class="fas fa-user"></i>&nbsp;
							{% if request.user.first_name or request.user.last_name %}
							{{request.user.first_name}} {{request.user.last_name}}
							{% else %}
							{{request.user.username}}
							{% endif %}
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
							<a class="dropdown-item" href="{% url 'account:view_profile' request.user %}"><i
									class="fas fa-eye"></i>&nbsp;&nbsp;View Profile</a>
							<a class="dropdown-item" href="{% url 'account:password_change' %}"><i
									class="fas fa-key"></i>&nbsp;&nbsp;Change Password</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="{% url 'account:logout' %}"><i
									class="fas fa-sign-out-alt"></i>&nbsp;&nbsp;Logut</a>
						</div>
					</li>
					{% endif %}
					{% if not request.user.is_authenticated and not "/account/login" in request.get_full_path %}
					<form method="post" action="{% url 'account:login' %}" class="form-inline my-2 my-lg-0">
						{% csrf_token %}
						<input class="form-control mr-sm-2" type="text" name="username" placeholder="Username" required>
						<input class="form-control mr-sm-2" type="password" name="password" placeholder="Password"
							required>
						<button type="submit" class="btn btn-primary">Login <i class="fas fa-sign-in-alt"></i></button>
					</form>
					{% endif %}
					{% if not request.user.is_authenticated and not "/account/register" in request.get_full_path %}
					<li class="nav-item ml-2">
						<a class="btn btn-primary" href="{% url 'account:register' %}">Register <i
								class="fa fa-user-plus" aria-hidden="true"></i></a>
					</li>
					{% endif %}
				</ul>
			</div>
		</nav>
		<div class="clearfix"></div>
		<section class="wrapper_section py-5">
			<div class="row">
				<div class="col-md-12">
					<div class="row">
						<div class="col-md-6 offset-md-3">
							{% if messages %}
							{% for message in messages %}
							{% if message.tags %}
							<div class="alert {{ message.tags }} {% endif %} alert-dismissible">
								<button type="button" class="close" data-dismiss="alert">&times;</button>
								{% if message.tags == "alert-danger" %}
								<strong> Error: </strong>
								{{ message|safe|linebreaksbr }}
								{% elif message.tags == "alert-success" or message.tags == "alert-info" %}
								<strong> Success: </strong>
								{{ message|safe|linebreaksbr }}
								{% elif message.tags == "alert-warning" %}
								<strong> Warning: </strong>
								{{ message|safe|linebreaksbr }}
								{% endif %}
							</div>
							{% endfor %}
							{% endif %}
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-2">
					{% block left_sidebar %} {% endblock %}
				</div>
				<div class="col-md-8">
					{% block content %} {% endblock %}
				</div>
				<div class="col-md-2">
					{% block right_sidebar %} {% endblock %}
				</div>
			</div>
		</section>
		<div class="clearfix"></div>
		<!-- Footer -->
		<footer style="color:#fff" class="page-footer font-small bg-dark">
			<!-- Footer Links -->
			<div class="container text-center text-md-left">

				<!-- Grid row -->
				<div class="row">

					<!-- Grid column -->
					<div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

						<!-- Content -->
						<h6 class="text-uppercase font-weight-bold mt-2">Donate Us</h6>
						<hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
						<div class="paypal_button">
				          <!-- Set up a container element for the button -->
				          <div id="paypal-button-container"></div>

				          <!-- Include the PayPal JavaScript SDK -->
				          <script src="https://www.paypal.com/sdk/js?client-id=sb&currency=USD"></script>

				          <script>
				            // Render the PayPal button into #paypal-button-container
				            paypal
				              .Buttons({
				                // Set up the transaction
				                createOrder: function(data, actions) {
				                  return actions.order.create({
				                    purchase_units: [
				                      {
				                        amount: {
				                          value: "0.01"
				                        }
				                      }
				                    ]
				                  });
				                },

				                // Finalize the transaction
				                onApprove: function(data, actions) {
				                  return actions.order.capture().then(function(details) {
				                    // Show a success message to the buyer
				                    alert(
				                      "Transaction completed by " +
				                        details.payer.name.given_name +
				                        "!"
				                    );
				                  });
				                }
				              })
				              .render("#paypal-button-container");
				          </script>
				        </div>

					</div>
					<!-- Grid column -->

					<!-- Grid column -->
					<div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-2 mb-2">

						<!-- Links -->
						<h6 class="text-uppercase font-weight-bold">Products</h6>
						<hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
						<p>
							<a href="#">Product 1</a>
						</p>
						<p>
							<a href="#">Product 2</a>
						</p>
						<p>
							<a href="#">Product 3</a>
						</p>
						<p>
							<a href="#">Product 4</a>
						</p>

					</div>
					<!-- Grid column -->

					<!-- Grid column -->
					<div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-2 mt-2">

						<!-- Links -->
						<h6 class="text-uppercase font-weight-bold">Useful links</h6>
						<hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
						<p>
							<a href="#">Link 1</a>
						</p>
						<p>
							<a href="#">Link 2</a>
						</p>
						<p>
							<a href="#">Link 3</a>
						</p>
						<p>
							<a href="#">Link 4</a>
						</p>

					</div>
					<!-- Grid column -->

					<!-- Grid column -->
					<div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-2 mt-2">

						<!-- Links -->
						<h6 class="text-uppercase font-weight-bold mt-2">Contact</h6>
						<hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
						<p>
							<i class="fas fa-home mr-3"></i> Dhaka, Bangladesh</p>
						<p>
							<i class="fas fa-envelope mr-3"></i> almasud.arm@gmail.com</p>
						<p>
							<i class="fas fa-phone mr-3"></i> + 880 1737 606053</p>

					</div>
					<!-- Grid column -->

				</div>
				<!-- Grid row -->

			</div>
			<!-- Footer Links -->

			<!-- Copyright -->
			<div class="footer-copyright text-center py-3">&copy; 2019 Copyright:
				<a target="_blank" href="https://facebook.com/almasud.arm"> Abdullah Almasud</a>
			</div>
			<!-- Copyright -->

		</footer>
		<!-- Footer -->
	</div>
</body>

</html>