account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.contrib import messages
from . import views
from django.contrib.auth.forms import PasswordChangeForm
from .forms import (
	UserLoginForm, UserPasswordResetForm, UserPasswordChangeForm,
	UserSetPasswordForm,
)


app_name = 'account'


urlpatterns = [
	path('login/', auth_views.LoginView.as_view(
		authentication_form=UserLoginForm,
		template_name='account/login.html',
		), name='login'
	),
	path('logout/', auth_views.LogoutView.as_view(
		next_page='account:login',
		), name='logout'),
	path('password_change/', auth_views.PasswordChangeView.as_view(
			template_name='account/password_change.html',
			form_class=UserPasswordChangeForm,
			success_url=reverse_lazy('account:password_change_done'),
		), name='password_change'
	),
	path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(
			template_name='account/password_change_done.html',	
		), name='password_change_done'
	),
	path('password_reset/', auth_views.PasswordResetView.as_view(
		form_class=UserPasswordResetForm,
		template_name='account/password_reset.html',
		success_url=reverse_lazy('account:password_reset_done'),
		email_template_name='account/password_reset_email.html',
		), 
		name='password_reset'
	),
	path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
		template_name='account/password_reset_done.html'
		), 
		name='password_reset_done'
	),
	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
		form_class=UserSetPasswordForm,
		template_name='account/password_reset_confirm.html',
		success_url=reverse_lazy('account:password_reset_complete'),
		), 
		name='password_reset_confirm'
	),
	path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
		template_name='account/passowrd_reset_complete.html'
		), 
		name='password_reset_complete'
	),
	path('register/', views.UserCreate.as_view(), name='register'),
	path('<slug:username>/', views.ProfileView.as_view(), name='view_profile'),
	path('profile/edit/', views.update_profile, name='edit_profile'),
]

blog/urls.py
from django.urls import path, re_path
from . import views as blog_views

app_name = 'blog'  # Namespace.

urlpatterns = [
    path('', blog_views.PostList.as_view(), name='post_view'),
    path('draft/', blog_views.DraftPostList.as_view(), name='draft_post_view'),
    path('published/', blog_views.PublishedPostList.as_view(), name='published_post_view'),
    path('post/<year>/<month>/<day>/<slug:slug>/', blog_views.DetailsPostView.as_view(), name='post_details_view'),
    path('post/add/', blog_views.PostCreate.as_view(), name='post_add'),
    path('post/<int:pk>/edit/', blog_views.PostUpdate.as_view(), name='post_update'),
    path('post/<int:pk>/published/', blog_views.PostPublish.as_view(), name='post_published'),
    path('post/<int:pk>/delete/', blog_views.PostDelete.as_view(), name='post_delete'),
    path('comment/approve/<int:post_pk>/<int:comment_pk>/', blog_views.ApprovedComment.as_view(), name='comment_approve'),
    path('comment/remove/<int:post_pk>/<int:comment_pk>/', blog_views.RemoveComment.as_view(), name='comment_remove'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import Post, Comment
# For Form Validation
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import re
# From python
from datetime import datetime
from datetime import timedelta


class PostForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Set existing photo as old_photo for later use in view
        self.old_photo = self.instance.photo

    class Meta:
        model = Post
        fields = ('title', 'text', 'photo',)

    title = forms.CharField(required=True, max_length=30,
                            help_text='Enter maximum 30 characters.',
                            widget=forms.TextInput(attrs={
                                'class': 'form-control', 'placeholder': 'Enter a post title...',
                            })
                            )

    text = forms.CharField(required=True,
                           widget=forms.Textarea(attrs={
                               'class': 'form-control', 'placeholder': 'Write something...',
                           }),
                           )

    photo = forms.FileField(required=False, label='Upload a photo',
                            help_text="Allowed extentions: ['jpg', 'jpeg', 'png']",
                            widget=forms.FileInput(attrs={
                                'class': 'form-control-file',
                            }),
                            )

    def clean_title(self):
        title = self.cleaned_data['title']
        pattern = r'^[A-Za-z]'
        if not re.match(pattern, title):
            raise ValidationError(
                _('Title cannot start with number!')
            )
        return title

    def clean_text(self):
        text = self.cleaned_data['text']
        return text

    def clean_photo(self):
        # photo attribute contain old image if not select any new
        photo = self.cleaned_data['photo']
        return photo


class LoginForm(forms.Form):

    username = forms.CharField(label="Username", required=True, max_length=30,
                               widget=forms.TextInput(attrs={
                                   'class': 'form-control', 'placeholder': 'Enter Username',
                               }),
                               )

    password = forms.CharField(label="Password", required=True, max_length=30,
                               widget=forms.PasswordInput(attrs={
                                   'class': 'form-control', 'placeholder': 'Enter Password',
                               }),
                               )


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

    text = forms.CharField(required=True, label='Comment',
                           widget=forms.Textarea(attrs={
                               'class': 'form-control', 'rows': '5',
                               'placeholder': 'Write something about this post...',
                           }),
                           )

    def clean_text(self):
        text = self.cleaned_data['text']
        return text

blog/views.py
from django.shortcuts import (
    render, get_object_or_404, redirect
)
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.views.generic import ListView, DetailView
from django.views.generic.base import RedirectView
from django.views.generic.edit import (
    CreateView, UpdateView, DeleteView, FormMixin
)
from django.contrib.auth.views import LoginView
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.urls import reverse, reverse_lazy
from .models import Post, Comment
from .forms import PostForm, LoginForm, CommentForm
from website.utils import login_required
import os
from django.contrib.auth.models import User


# This class describes all published posts of all users
class PostList(ListView):
    model = Post
    paginate_by = 5
    context_object_name = "posts"

    def get_queryset(self):
        return Post.objects.filter(published__lte=timezone.now())


# This class shows all draft post
class PublishedPostList(ListView):
    model = Post
    paginate_by = 5

    context_object_name = "published_posts"

    def get_queryset(self):
        return Post.objects.filter(published__isnull=False, author=self.request.user).order_by('-published')

    # Decorate every instance of the class.
    @method_decorator(login_required(login_url='account:login', message="Sorry!\nYou must login to view your published posts."))
    # This method accepts a request and returns a HTTP response.
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# This class shows all draft post
class DraftPostList(ListView):
    model = Post
    paginate_by = 5

    context_object_name = "draft_posts"

    def get_queryset(self):
        return Post.objects.filter(published__isnull=True, author=self.request.user).order_by('-created')

    @method_decorator(login_required(login_url='account:login', message="Sorry!\nYou must login to view your draft posts."))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# This class publish a draft post
class PostPublish(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        post = get_object_or_404(Post, pk=kwargs['pk'])
        post.published = timezone.now()
        post.save()
        self.url = post.get_absolute_url()
        return super().get_redirect_url(*args, **kwargs)


# This class approves a post comment
class ApprovedComment(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        comment = get_object_or_404(Comment, pk=kwargs['comment_pk'])
        post = Post.objects.get(id=kwargs['post_pk'])
        self.url = post.get_absolute_url()

        if self.request.user == post.author:
            comment.approve()
            messages.success(self.request, 'Comment is approved!')
            return super().get_redirect_url(*args, **kwargs)
        else:
            messages.error(
                self.request, 'Sorry! You have not permission.\nOnly post author can approve this comment.')
            return super().get_redirect_url(*args, **kwargs)


# This class removes a comment
class RemoveComment(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        comment = get_object_or_404(Comment, pk=kwargs['comment_pk'])
        post = Post.objects.get(id=kwargs['post_pk'])
        self.url = post.get_absolute_url()

        if self.request.user == post.author or self.request.user == comment.author:
            comment.delete()
            messages.success(self.request, 'Comment is removed.')
            return super().get_redirect_url(*args, **kwargs)
        else:
            messages.error(
                self.request, 'Sorry! You have not permission to remove this comment.')
            return super().get_redirect_url(*args, **kwargs)


"""
We can inherit only one generic view - that is, only one parent 
class may inherit from View and the rest (if any) should be mixins.
(Mixins are a form of multiple inheritance where behaviors and 
attributes of multiple parent classes can be combined and are an 
excellent way of reusing code across multiple classes.)
"""


# This class is used to show the details of a post and
# write a comment in those post.
class DetailsPostView(FormMixin, DetailView):
    model = Post
    form_class = CommentForm
    template_name = 'blog/post_details.html'

    def get_success_url(self):
        return self.object.get_absolute_url()

    # A dictionary used as a template context
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['form'] = self.get_form()
        return context

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = self.object
        comment.author = self.request.user.username
        form.save()
        messages.success(
            self.request, 'Comment successful!\nYour comment will display after approved.')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(
            self.request, 'Comment submission is invalid!\nPlease correct the error in below.')
        return super().form_invalid(form)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def dispatch(self, *args, **kwargs):
        self.object = self.get_object()
        post = get_object_or_404(Post, pk=self.object.pk)
        # For unpublished post.
        if post.published is None:
            if not self.request.user.is_authenticated:
                messages.error(
                    self.request, "Sorry!\nYou must login to view any draft post.")
                return redirect('account:login')
            # For except author
            if not self.request.user == post.author:
                messages.error(
                    self.request, "Sorry!\nYou have not permission to view this post.")
                return redirect('blog:post_view')
        # For published post.
        return super().dispatch(*args, **kwargs)


# This class is used to create a post
class PostCreate(CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        if self.request.POST.get('submit') == "publish":
            post.published = timezone.now()
        post.save()
        messages.success(self.request, 'Post successfully added.')
        return super().form_valid(form)

    def form_invalid(self, form):
        self.object = None
        messages.error(
            self.request, 'Invalid form submission !\nPlease correct the error in below.')
        return super().form_invalid(form)

    def post(self, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    # Decorate every instance of the class.
    @method_decorator(login_required(login_url='account:login', message="Sorry!\nYou must login to add any post."))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


# This class is used to update a post
class PostUpdate(UpdateView):
    model = Post
    form_class = PostForm
    template_name_suffix = '_form'

    def form_valid(self, form):
        post = form.save(commit=False)
        # photo attribute contain old image if not select any new
        new_photo = self.request.FILES.get('photo')  # New photo
        old_photo = form.old_photo  # Get old photo from form
        photo_remove_checked = bool(self.request.POST.get('remove_checked'))
        # Remove photo if checked clear
        if photo_remove_checked:
            if os.path.isfile(post.photo.path):
                os.remove(post.photo.path)
                post.photo = None
        # Remove old photo if upload new one
        if new_photo:
            if old_photo:
                if os.path.isfile(old_photo.path):
                    os.remove(old_photo.path)
        form.save()
        messages.success(self.request, 'Post successfully updated.')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(
            self.request, 'Invalid form submission !\nPlease correct the error in below.')
        return super().form_invalid(form)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    # Decorate every instance of the class.
    @method_decorator(login_required(login_url='account:login', message="Sorry!\nYou must login to update any post."))
    def dispatch(self, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author == self.request.user:
            return super().dispatch(*args, **kwargs)
        else:
            messages.error(
                self.request, 'Sorry! You have not permission.\nOnly author can edit this post.')
            return HttpResponseRedirect(self.object.get_absolute_url())


# This class is used to remove a post
class PostDelete(DeleteView):
    model = Post
    template_name = 'blog/post_details.html'

    def get_success_url(self):
        messages.success(self.request, 'Post deleted successfully.')
        return reverse_lazy('blog:post_view')

    def delete(self, request, *args, **kwargs):
        if self.object.author == request.user:
            self.object.delete()
            if self.object.photo:
                if os.path.isfile(self.object.photo.path):
                    os.remove(self.object.photo.path)
            return HttpResponseRedirect(self.get_success_url())
        else:
            messages.error(

blog/templates/blog/post_details.html
{% extends 'base.html' %}

{% block title%} {{post.title}} {% endblock %}
{%block content %}
<article class="post">
	{% if request.user.username == post.author.username %}
		<div class="float-right">
			<a title="Edit post" class="btn btn-primary" href="{% url 'blog:post_update' post.pk %}"><i
					class="far fa-edit"></i></a>
			{% if not post.published %}
			<a class="btn btn-success" href="{% url 'blog:post_published' post.pk %}" data-toggle="confirmation"
				data-title="Publish this post?" data-popout="true" data-singleton="true"><i class="fas fa-upload"></i></a>
			{% endif %}
			<form id="delete_form" action="{% url 'blog:post_delete' post.pk %}" style="display:inline-block" method="post">
				{% csrf_token %}
				<button type="submit" class="btn btn-danger" data-toggle="confirmation" data-title="Delete this post?"
					data-popout="true" data-singleton="true">
					<i class="fas fa-trash-alt"></i>
				</button>
			</form>
		</div>
	{% endif %}
	<h2>{{post.title}}</h2>
	<div class="date">
		{% if not post.published %}
		<p>Created: {{post.created|date:'d-m-Y'}}</p>
		{% else %}
		<p>Published: {{post.published}}</p>
		{% endif %}
		<p>Posted by:
			{% if post.author.first_name or post.author.last_name %}
			<a href="{% url 'account:view_profile' post.author.username %}">{{post.author.first_name}}
				{{post.author.last_name}}</a>
			{% else %}
			<a href="{% url 'account:view_profile' post.author.username %}">{{post.author.username}}</a>
			{% endif %}
		</p>
	</div>
	{% if post.photo %}
	<div>
		<img src="{{ post.photo.url }}" alt="Post Photo" class="rounded" style="width:auto; height: 250px">
	</div><br>
	{% endif %}
	<p>{{post.text|linebreaksbr}}</p>
</article>
<hr>
<section class="comment_section">
	<div class="row">
		<div class="col-md-6">
			{% if request.user.is_authenticated %}
			<div class="add_comment">
				<h4>Add comment</h4>
				<form method="POST">
					{% csrf_token %}
					{% for field in form %}
					<div class="form-group">
						{{ field.label_tag }}
						{{ field }}
						{% for error in field.errors %}
						<p class="text-danger">
							<strong>Error:</strong>
							{{ error|escape }}
						</p>
						{% endfor %}
						{% if field.help_text %}
						<small class="form-text text-muted">
							{{ field.help_text|safe }}
						</small>
						{% endif %}
					</div>
					{% endfor %}
					<button type="submit" class="btn btn-success" name="submit" value="save">Add comment</button>
				</form>
			</div>
			{% endif %}
		</div>
	</div><br>
	<div class="row">
		<div class="col-md-6">
			<h4>Comments of this post:</h4>
			{% for comment in post.comments.all %}
			{% if comment.approved_comment or request.user == comment.author or request.user == post.author %}
			<div class="comment">
				<strong>{{comment.author}}</strong>
				<div class="date">
					{{comment.created}}
					<!-- For approve and delete button -->
					{% if not comment.approved_comment and request.user == post.author %}
					<a href="{% url 'blog:comment_approve'  post_pk=comment.post.pk comment_pk=comment.pk %}"
						class="btn btn-primary btn-sm" data-toggle="confirmation" data-title="Approve this comment?"
						data-popout="true" data-singleton="true"><i class="fas fa-check"></i></a>
					{% endif %}
					{% if request.user == post.author or request.user == comment.author %}
					<a href="{% url 'blog:comment_remove' post_pk=comment.post.pk comment_pk=comment.pk %}"
						class="btn btn-danger btn-sm" data-toggle="confirmation" data-title="Delete this comment?"
						data-popout="true" data-singleton="true"><i class="fas fa-trash-alt"></i></a>
					{% endif %}
				</div>
				<p>{{comment.text|linebreaksbr}}</p>
			</div>
			{% endif %}
			{% empty %}
			<p>No comments here yet :(</p>
			{% endfor %}
		</div>
	</div>
</section>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block title %} Blog {% endblock %}
{% block navbar %}
{% if request.user.is_authenticated %}
<li class="nav-item mr-2">
	<a title="Add a post" class="btn btn-primary" href="{% url 'blog:post_add' %}"><i class="fas fa-plus"></i>Add a
		post</a>
</li>
{% endif %}
{% endblock %}
{% block content %}
<div class="col-md-12">
	<nav>
		<div class="nav nav-tabs" id="nav-tab" role="tablist">
			<a class="nav-item nav-link {% if not "/publish" in request.get_full_path and not "/draft" in request.get_full_path %} active {% endif %}" id="nav-all_post-tab" data-toggle="tab" href="#nav-all_post" role="tab"
				aria-controls="nav-all_post" aria-selected="true">All post</a>
			{% if request.user.is_authenticated %}
			<a class="nav-item nav-link {% if request.user.is_authenticated and "/publish" in request.get_full_path %} active {% endif %}" id="nav-published_post-tab" data-toggle="tab" href="#nav-published_post"
				role="tab" aria-controls="nav-published_post" aria-selected="true">Publish post</a>
			<a class="nav-item nav-link {% if request.user.is_authenticated and "/draft" in request.get_full_path %} active {% endif %}" id="nav-unpublish_post-tab" data-toggle="tab" href="#nav-unpublish_post"
				role="tab" aria-controls="nav-unpublish_post" aria-selected="false">Unpublish post</a>
			{% endif %}
		</div>
	</nav>
	<script type="text/javascript">
		// For Published post
		document.getElementById("nav-all_post-tab").onclick = function () {
			window.open("{% url 'blog:post_view' %}", "_self");
			this.addAttribute("class", "active");
		}
		// For Published post
		document.getElementById("nav-published_post-tab").onclick = function () {
			window.open("{% url 'blog:published_post_view' %}", "_self");
		}
		// For Unpublish post
		document.getElementById("nav-unpublish_post-tab").onclick = function () {
			window.open("{% url 'blog:draft_post_view' %}", "_self");
		}
	</script>
	{% if draft_posts %}
	{% for post in draft_posts %}
	<article class="post">
		<h2><a
				href="{% url 'blog:post_details_view' post.created|date:"Y" post.created|date:"m" post.created|date:"d" post.slug %}">{{post.title}}</a>
		</h2>
		<div class="date">
			<p>Created: {{post.created|date:'d-m-Y'}}</p>
			<p>Posted by:
				{% if post.author.first_name or post.author.last_name %}
				<a href="{% url 'account:view_profile' post.author.username %}">{{post.author.first_name}}
					{{post.author.last_name}}</a>
				{% else %}
				<a href="{% url 'account:view_profile' post.author.username %}">{{post.author.username}}</a>
				{% endif %}
			</p>
		</div>
		{% if post.photo %}
		<div>
			<a
				href="{% url 'blog:post_details_view' post.created|date:"Y" post.created|date:"m" post.created|date:"d" post.slug %}">
				<img src="{{ post.photo.url }}" alt="Post Photo" class="rounded" style="width:auto; height: 250px">
			</a>
		</div><br>
		{% endif %}
		{% if post.text|length > 500 %}
		<p>{{post.text|linebreaksbr|truncatewords:50}} <a class="btn btn-success btn-sm"
				href="{% url 'blog:post_details_view' post.created|date:"Y" post.created|date:"m" post.created|date:"d" post.slug %}">Red
				More</a></p>
		{% else %}
		<p>{{post.text|linebreaksbr}}</p>
		{% endif %}
	</article>
	{% endfor %}
	{% elif published_posts %}
	{% for post in published_posts %}
	<article class="post">
		<h2><a
				href="{% url 'blog:post_details_view' post.created|date:"Y" post.created|date:"m" post.created|date:"d" post.slug %}">{{post.title}}</a>
		</h2>
		<div class="date">
			<p>Published: {{post.published}}</p>
			<p>Posted by:
				{% if post.author.first_name or post.author.last_name %}
				<a href="{% url 'account:view_profile' post.author.username %}">{{post.author.first_name}}
					{{post.author.last_name}}</a>
				{% else %}
				<a href="{% url 'account:view_profile' post.author.username %}">{{post.author.username}}</a>
				{% endif %}
			</p>
		</div>
		{% if post.photo %}
		<div>
			<a
				href="{% url 'blog:post_details_view' post.created|date:"Y" post.created|date:"m" post.created|date:"d" post.slug %}">
				<img src="{{ post.photo.url }}" alt="Post Photo" class="rounded" style="width:auto; height: 250px">
			</a>
		</div><br>
		{% endif %}
		{% if post.text|length > 500 %}
		<!-- for post length greater than 50 words -->
		<p>{{post.text|linebreaksbr|truncatewords:50}} <a class="btn btn-success btn-sm"
				href="{% url 'blog:post_details_view' post.created|date:"Y" post.created|date:"m" post.created|date:"d" post.slug %}">Red
				More</a></p>
		{% else %}
		<!-- for post length less than 50 words -->
		<p>{{post.text|linebreaksbr}}</p>
		{% endif %}
		<!-- Comment link start -->
		{% if post.comments.count %}
		{% if request.user == post.author or request.user == comment.author %}
		<a class="text-primary"
			href="{% url 'blog:post_details_view' post.created|date:"Y" post.created|date:"m" post.created|date:"d" post.slug %}">
			{% if post.comments.count == 1 %}
			{{post.comments.count}} Comment</a>.
		{% else %}
		{{post.comments.count}} Comments</a>.
		{% endif %}
		{% elif post.comments.approved_comment_count > 0 %}
		<a class="text-primary"
			href="{% url 'blog:post_details_view' post.created|date:"Y" post.created|date:"m" post.created|date:"d" post.slug %}">
			{% if post.comments.approved_comment_count == 1 %}
			{{post.comments.approved_comment_count}} Comment</a>.
		{% else %}
		{{post.comments.approved_comment_count}} Comments</a>.
		{% endif %}
		{% else %}
		<p class="text-primary">No comments.</p>
		{% endif %}
		{% else %}
		<p class="text-primary">No comments.</p>
		{% endif %}
		<!-- Comment link end -->
	</article>
	{% endfor %}
	{% elif posts %}
	{% for post in posts %}
	<article class="post">
		<h2><a
				href="{% url 'blog:post_details_view' post.created|date:"Y" post.created|date:"m" post.created|date:"d" post.slug %}">{{post.title}}</a>
		</h2>
		<div class="date">
			<p>Published: {{post.published}}</p>
			<p>Posted by:
				{% if post.author.first_name or post.author.last_name %}
				<a href="{% url 'account:view_profile' post.author.username %}">{{post.author.first_name}}
					{{post.author.last_name}}</a>
				{% else %}
				<a href="{% url 'account:view_profile' post.author.username %}">{{post.author.username}}</a>
				{% endif %}
			</p>
		</div>
		{% if post.photo %}
		<div>
			<a
				href="{% url 'blog:post_details_view' post.created|date:"Y" post.created|date:"m" post.created|date:"d" post.slug %}">
				<img src="{{ post.photo.url }}" alt="Post Photo" class="rounded" style="width:auto; height: 250px">
			</a>
		</div><br>
		{% endif %}
		{% if post.text|length > 500 %}
		<!-- for post length greater than 50 words -->
		<p>{{post.text|linebreaksbr|truncatewords:50}} <a class="btn btn-success btn-sm"
				href="{% url 'blog:post_details_view' post.created|date:"Y" post.created|date:"m" post.created|date:"d" post.slug %}">Red
				More</a></p>
		{% else %}
		<!-- for post length less than 50 words -->
		<p>{{post.text|linebreaksbr}}</p>
		{% endif %}
		<!-- Comment link start -->
		{% if post.comments.count %}
		{% if request.user == post.author or request.user == comment.author %}
		<a class="text-primary"
			href="{% url 'blog:post_details_view' post.created|date:"Y" post.created|date:"m" post.created|date:"d" post.slug %}">
			{% if post.comments.count == 1 %}
			{{post.comments.count}} Comment</a>.
		{% else %}
		{{post.comments.count}} Comments</a>.
		{% endif %}
		{% elif post.comments.approved_comment_count > 0 %}
		<a class="text-primary"
			href="{% url 'blog:post_details_view' post.created|date:"Y" post.created|date:"m" post.created|date:"d" post.slug %}">
			{% if post.comments.approved_comment_count == 1 %}
			{{post.comments.approved_comment_count}} Comment</a>.
		{% else %}
		{{post.comments.approved_comment_count}} Comments</a>.
		{% endif %}
		{% else %}
		<p class="text-primary">No comments.</p>
		{% endif %}
		{% else %}
		<p class="text-primary">No comments.</p>
		{% endif %}
		<!-- Comment link end -->
	</article>
	{% endfor %}
	{% else %}
	<div class="alert alert-info alert-dismissible">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<strong>Opps!</strong> There are no post yet.
	</div>
	{% endif %}
	<nav class="pagination_section" aria-label="...">
		{% if is_paginated %}
		<ul class="pagination justify-content-center">
			{% if page_obj.has_previous %}
			<li class="page-item">
				<a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
			</li>
			{% else %}
			<li class="page-item disabled">
				<span class="page-link">Previous</span>
			</li>
			{% endif %}
			{% for i in paginator.page_range %}
			{% if page_obj.number == i %}
			<li class="page-item active">
				<span class="page-link">
					{{ i }}
					<span class="sr-only">(current)</span>
				</span>
			</li>
			{% else %}
			<li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
			{% endif %}
			{% endfor %}
			{% if page_obj.has_next %}
			<li class="page-item">
				<a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
			</li>
			{% else %}
			<li class="page-item disabled">
				<span class="page-link">Next</span>
			</li>
			{% endif %}
		</ul>
		{% endif %}
	</nav>
</div>
{% endblock content %}